---
- name: update apt
  apt: update_cache=yes cache_valid_time=86400

- name: install base packages
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - sudo

- name: generate en_CA.UTF
  sudo: yes
  shell: locale-gen en_CA.UTF-8
