sudo : required
dist: trusty

services:
  - docker

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}

before_install:
# Download and unpack the stack available
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack
# Disable conflicting services
  - sudo service postgresql stop

install:
  - (cd terrarium && stack setup --no-terminal)

script:
  - (cd terrarium && stack test --no-terminal)
  - (cd terrarium && stack build --no-terminal)
  - (cd terrarium && mkdir -p dist/x86_64-linux/ && stack install --local-bin-path dist/x86_64-linux --no-terminal)
  - (mkdir postgres-migration && cd postgres-migration && git clone https://github.com/crosscent/haskell_postgres_migration.git .)
  - (cd postgres-migration && stack install --local-bin-path ../terrarium/dist/x86_64-linux --no-terminal)
  - docker-compose build
  - docker-compose up -d

after_script:
 - docker-compose down
