---
- name: stack setup terrarium-api
  command: stack setup --allow-different-user chdir={{document_root}}/terrarium
  sudo: no

- name: create directory for terrarium-api
  file: path={{document_root}}/terrarium/dist/x86_64-linux state=directory

- name: compile terrarium-api
  command: stack install --allow-different-user --local-bin-path {{document_root}}/terrarium/dist/x86_64-linux chdir={{document_root}}/terrarium
  sudo: no
