---
- hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    home_root: /home/vagrant
    document_root: /home/vagrant/bettermatter
    binary_root: /home/vagrant/binaries

  roles:
    - docker-setup
    - haskell-related
    - compiles
    - docker-build
