---
- name: install haskell
  apt: name=haskell-platform state=installed

- name: add apt key for stack
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=575159689BEFB442 state=present

- name: add stack to fpco.list
  shell: echo 'deb http://download.fpcomplete.com/ubuntu trusty main'|sudo tee /etc/apt/sources.list.d/fpco.list
  sudo: yes

- name: install stack
  apt: name=stack state=installed update_cache=yes
